version: '3'

services:

    pizza-nginx:
        container_name: 'pizza-nginx'
        image: 'nginx'
        restart: always
        ports:
            - '80:80'
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - pizza-network

    pizza-php-fpm1:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: 'pizza-php-fpm1'
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - pizza-network

    pizza-php-fpm2:
        container_name: 'pizza-php-fpm2'
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - pizza-network

    pizza-php-fpm3:
        container_name: 'pizza-php-fpm3'
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - pizza-network

#    pizza-memcached:
#        container_name: 'pizza-memcached'
#        image: 'memcached:latest'
#        ports:
#            - '11211:11211'
#        networks:
#            - pizza-network
#
#    pizza-redis:
#        container_name: 'pizza-redis'
#        image: 'redis:latest'
#        volumes:
#            -   'sail-redis:/data'
#        ports:
#            - '6379:6379'
#        networks:
#            - pizza-network
#
#    pizza-postgres:
#        container_name: 'pizza-postgres'
#        image: 'postgres:14'
#        restart: always
#        ports:
#            - '5432:5432'
#        environment:
#            - POSTGRES_DB=sail
#            - POSTGRES_USER=laravel
#            - POSTGRES_PASSWORD=laravel
#        volumes:
#            - 'sail-pgsql:/var/lib/postgresql/data'

networks:
    pizza-network:
        driver: bridge
